apiVersion: v1
kind: Service
metadata:
  name: the-redis-server
spec:
  type: ClusterIP
  selector:
    app: redispod
  ports:
    - name: http
      port: 6379
      targetPort: 6379
      protocol: TCP

